# fly.toml app configuration file generated for test-play-test on 2023-06-27T21:00:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "test-play-test"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[env]
  IS_CONTROLLER = "true"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1
    soft_limit = 1
