# fly.toml app configuration file generated for winglang-playground on 2023-07-09T14:28:42+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "winglang-playground"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[env]
  IS_CONTROLLER = "true"
  QUEUE_SIZE = "80"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 2

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[metrics]
  port = 3000
  path = "/metrics"
