name: Build

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  preview-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build playground
        run: npx turbo run tsc build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Destory preview app
        if: ${{ github.event.action == 'closed' }}
        run: |
          app=pr-${{github.event.number}}-playground
          flyctl apps destroy "$app" -y
        working-directory: apps/server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy preview app
        if: ${{ github.event.action != 'closed' }}
        run: |
          app=pr-${{github.event.number}}-playground
          if ! flyctl status --app "$app"; then
            flyctl launch --no-deploy --copy-config --name "$app" --image-label latest
          fi
          flyctl deploy --config ./fly.preview.toml --app "$app" --image-label latest --vm-memory 512 --strategy immediate
          flyctl scale count 1 --yes --app "$app"
        working-directory: apps/server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  test:
    if: ${{ github.event.action != 'closed' }}
    needs: [preview-app]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build playground
        run: npx turbo run tsc build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playground tests
        run: npx playwright test
        working-directory: apps/playground
      - name: Run Tour tests
        run: npx playwright test --pass-with-no-tests
        working-directory: apps/tour
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: apps/*/playwright-report/
          retention-days: 30
  deploy-play:
    if: ${{ github.event.action != 'closed' }}
    needs: [preview-app]
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PLAYGROUND_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        # working-directory: apps/play
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }} -e VITE_CONSOLE_SERVER_URL=https://pr-${{github.event.number}}-${{github.event.repository.owner}}-${{github.event.repository.name}}.fly.dev
        # working-directory: apps/play
  deploy-learn:
    if: ${{ github.event.action != 'closed' }}
    needs: [preview-app]
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_LEARN_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        # working-directory: apps/tour
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }} -e VITE_CONSOLE_SERVER_URL=https://pr-${{github.event.number}}-${{github.event.repository.owner}}-${{github.event.repository.name}}.fly.dev
        # working-directory: apps/tour
