name: Release Wing Playground
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  release:
    name: Release Wing Playground
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Update assets
        run: npx tsx scripts/updatePlayground.ts
        env:
          GITHUB_TOKEN: ${{ secrets.PROJEN_GITHUB_TOKEN }}
      - name: Build playground
        run: npm run build
      - name: "Publish Wing Playground"
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          github-comment: false
          vercel-args: "--prod "
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          commit-message: |-
            feat: update playground

            Updates the Wing playground. See details in [workflow run].

            [Workflow Run]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            ------

            *Automatically created via the "release" workflow*
          branch: github-actions/update-playground
          title: "feat: update playground"
          body: |-
            feat: update playground

            Updates the Wing playground. See details in [workflow run].

            [Workflow Run]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            ------

            *Automatically created via the "release" workflow*
          author: monabot <monabot@monada.co>
          committer: monabot <monabot@monada.co>
          signoff: true
          labels: documentation
          delete-branch: true