name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build playground
        run: npx turbo run tsc build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --image-label ${{ github.sha }} -e FLY_APPS_IMAGE=registry.fly.io/winglang-playground:${{ github.sha }}  --vm-memory 512
        working-directory: apps/server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          working_dir: apps/infra
          cdk_subcommand: 'diff'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          working_dir: apps/infra
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          actions_comment: false
          debug_log: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
  build-self-hosted:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install dependencies
        run: npm install
      - name: Build playground
        run: npx turbo run tsc build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          VITE_SELF_HOSTED: "true"
      - name: Copy playground and tour assets
        run: |
          cp -rf apps/playground/dist apps/server/play
          cp -rf apps/tour/dist apps/server/tour
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: wingcloudbot/playground
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: apps/server
          file: apps/server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
