name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build playground
        run: npx turbo run tsc build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --image-label ${{ github.sha }} -e FLY_APPS_IMAGE=registry.fly.io/winglang-playground:${{ github.sha }}  --vm-memory 512
        working-directory: apps/server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          working_dir: apps/infra
          cdk_subcommand: 'diff'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          working_dir: apps/infra
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          actions_comment: false
          debug_log: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
