name: Update Wing Version

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 * * * *

permissions:
  contents: write
  pull-requests: write

jobs:
  update-wing-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Update wing version
        run: pnpm update winglang @winglang/sdk
        working-directory: apps/playground
      - name: Build playground
        run: pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.PROJEN_GITHUB_TOKEN }}
      - name: Check Changed files
        uses: tj-actions/verify-changed-files@v14
        id: verify-changed-files
      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          commit-message: |-
            feat: update wing version
            Updates the Wing version. See details in [workflow run].
            [Workflow Run]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ------
            *Automatically created via the "update-wing" workflow*
          branch: github-actions/update-wing
          title: "feat: update wing version"
          body: |-
            feat: update wing version
            Updates the Wing version. See details in [workflow run].
            [Workflow Run]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ------
            *Automatically created via the "update-wing" workflow*
          author: monabot <monabot@monada.co>
          committer: monabot <monabot@monada.co>
          signoff: true
          labels: dependencies
          delete-branch: true
      - name: Enable Pull Request Automerge
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
      - name: Auto approve
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        run: gh pr review --approve "${{ steps.create-pr.outputs.pull-request-number }}" -R https://github.com/winglang/playground
        env:
          GH_TOKEN: ${{ secrets.APPROVALS_GITHUB_TOKEN }}
